name: Test Builds on all platforms

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build and test all platforms
    uses: ./.github/workflows/build_packages.yaml
